apiVersion: routing.router.io/v1alpha1
kind: ServiceRoute
metadata:
  name: test-workload-route
spec:
  serviceName: test-workload
  gatewayName: app-gateway-ingress
  environment: base
  application: workload-a
