apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-router.yaml

namespace: flux-system

configMapGenerator:
  - name: service-router-values
    files:
      - values.yaml=./values.yaml

configurations:
  - kustomizeconfig.yaml
