apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml
  - external-dns

configMapGenerator:
  - name: external-dns-values-
    files:
      - values.yaml=values.yaml

nameSuffix: ${DNS_REGION}

namespace: ns-${ENV_LETTER}-all-addon-flux-cluster-config-01

configurations:
  - ./kustomizeconfig.yaml
