apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-dns
spec:
  interval: 10m
  provider: azure
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://${TENANT}spfmcontainerregistry.azurecr.io/helm/charts/public/external-dns
  ref:
    # Use semantic versioning for chart version
    # Example: 1.14.x will match latest 1.14.z version
    semver: ${CHART_VERSION}
  verify:
    provider: cosign
