# This rule is not used by the project service-router-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the networking.platform.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: service-router-operator
    app.kubernetes.io/managed-by: kustomize
  name: servicerouter-editor-role
rules:
- apiGroups:
  - networking.platform.com
  resources:
  - servicerouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.platform.com
  resources:
  - servicerouters/status
  verbs:
  - get
