apiVersion: routing.router.io/v1alpha1
kind: Gateway
metadata:
  name: app-gateway-ingress
spec:
  controller: aks-istio-ingressgateway-internal
  #credentialName: cert-aks-ingress
  targetPostfix: internal
