name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18' # Specify the Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: |
          go test ./... -v

      - name: Build the operator
        run: go build -o service-router-operator ./cmd/main.go

      - name: Build Docker image
        run: |
          docker build -t myacr.azurecr.io/service-router-operator:latest .

      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login myacr.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push myacr.azurecr.io/service-router-operator:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy/manifests/