name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Build
        run: |
          go build -o service-router-operator ./cmd

      - name: Docker Build
        run: |
          docker build -t myacr.azurecr.io/service-router-operator:${{ github.ref }} .

      - name: Log in to ACR
        uses: docker/login-action@v1
        with:
          registry: myacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push myacr.azurecr.io/service-router-operator:${{ github.ref }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy/manifests/ --record

      - name: Notify Release
        run: |
          echo "Release ${{ github.ref }} has been deployed successfully."