name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install dependencies
        run: go mod tidy

      - name: Run security checks
        run: |
          gosec ./...
          staticcheck ./...
          go vet ./...

      - name: Check for vulnerabilities
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL your-image-name:latest || true

      - name: Upload security report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: security-report
          path: ./gosec-report.json
          if-no-files-found: error

      - name: Notify on failure
        if: failure()
        run: echo "Security checks failed. Please review the logs."